# Generated by Django 5.0.4 on 2024-04-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='surename',
            new_name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='surname',
            field=models.CharField(default=-1, max_length=45),
            preserve_default=False,
        ),
    ]
