# Generated by Django 5.0.2 on 2024-02-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('company', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Experience',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=15)),
                ('graded_university', models.CharField(choices=[('university pdp', 'PDP university'), ('university oxford', 'Oxford university')], max_length=150)),
            ],
            options={
                'db_table': 'Teacher',
            },
        ),
    ]
