# Generated by Django 5.0.2 on 2024-03-02 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(choices=[('pizza', 'Pizza'), ('somsa', 'Somsa'), ('cheese', 'Cheese')], max_length=150)),
                ('drinks', models.CharField(choices=[('fruit juice', 'Fruit Juice'), ('drink1', 'Drink1'), ('drink2', 'Drink2')], max_length=250)),
            ],
            options={
                'db_table': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=100)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('order_number', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering.user')),
            ],
            options={
                'db_table': 'OrderInfo',
            },
        ),
    ]
