# Generated by Django 5.0.2 on 2024-03-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='order_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
