# Generated by Django 5.0.2 on 2024-03-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_alter_user_order_number_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(choices=[('pizza', 'Pizza'), ('lagman', 'Lagmon'), ('cheese', 'Cheese')], max_length=150)),
                ('drinks', models.CharField(choices=[('fruit juice', 'Fruit Juice'), ('drink1', 'Drink1'), ('drink2', 'Drink2')], max_length=250)),
            ],
        ),
    ]
