# Generated by Django 5.0.2 on 2024-03-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0003_menu'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menu',
            table='Menu',
        ),
    ]
