# Generated by Django 5.0.2 on 2024-03-02 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0004_alter_menu_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userOrders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering.user')),
            ],
            options={
                'db_table': 'OrderInfo',
            },
        ),
    ]
